project:
  type: website
  output-dir: docs
website:
  announcement: 
    icon: megaphone
    dismissable: false
    content: "Hello Class! Welcome to OMIS-482! I hope you guys have a wonderful semester & All the Best!! -**Dr.B** "
    type: primary
    position: below-navbar
  page-navigation: true
  page-footer:
    background: "#343a40"
    right: "Created by: Venkata Surya Vineel Nekkanti"
    left: "&copy; Copyright 2024, Dr. B"
    center: "For Further Queries: bpalese@niu.edu"
  favicon: "images/logo_2.png"
  cookie-consent:
    type: implied
    style: interstitial
    palette: light
  google-analytics:
    tracking-id: "G-DRJBM9ZKMY"
    
  #navbar:
    #background: "#343a40"
    #title: "OMIS-482: Predictive Business Analytics With Machine Learning"
    #pinned: true
   # align: centre
    #tools:
    #    - icon: backpack-fill
    #      text: "Blackboard"
    #      url: https://webcourses.niu.edu/ultra/courses/_348339_1/outline
  sidebar:
    background: "#343a40" 
    logo: "images/logo_2.png"
    pinned: true
    align: centre
    style: docked
    search: true
    contents:
      - section: "Course Overview"
        contents:
        - href: course-overview.qmd
          text: Course Overview
        - href: index.qmd
          text: Faculty
        - href: "files/OMIS482_SyllabusSpring2024_BiagioPalese_03_29.pdf"
          text: Syllabus
          target: _blank
        - href: student-dashboard.qmd
          text: Dr.B's Leaderboard
        - href: useful-links.qmd
          text: Useful Links
      - section: "Course Materials"
        contents:
          - section: "Week 1"
            contents:
            - href: week1_materials_starter.qmd
              text: In-class Material
            - href: week1_materials_starter.qmd
              text: Weekly Activity
          - section: "Week 2"
            contents:
            - href: week1_materials_starter.qmd
              text: In-class Material
            - href: week1_materials_starter.qmd
              text: Weekly Activity
          - section: "Week 3"
            contents:
            - href: week1_materials_starter.qmd
              text: In-class Material
            - href: week1_materials_starter.qmd
              text: Weekly Activity              
      - section: "Backup Content"
        contents:
        - href: in_class.qmd
          text: In-class & Weekly
        - href: practice_R.qmd
          text: Practice R with WebR
        - href: practice_R_with_quarto-live.qmd
          text: Practice R with Quarto-Live


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    code-link: true
    css: styles.css
  
execute:
  freeze: auto

editor: visual